'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'

interface CustomFAQ {
  question: string
  answer: string
  source: 'auto' | 'manual'
}

interface FAQPanelProps {
  productId: string
  /** Auto-generated FAQs derived from product data (Score, kyselost, ...).
   *  Used as defaults when admin opens the panel for the first time. */
  autoGenerated: { question: string; answer: string }[]
  initialCustomFAQs: CustomFAQ[]
}

export function FAQPanel({ productId, autoGenerated, initialCustomFAQs }: FAQPanelProps) {
  const router = useRouter()
  // Build initial state: existing custom_faqs override auto, plus auto entries that aren't overridden
  const buildInitial = (): CustomFAQ[] => {
    if (initialCustomFAQs.length > 0) return initialCustomFAQs
    return autoGenerated.map(f => ({ question: f.question, answer: f.answer, source: 'auto' as const }))
  }
  const [faqs, setFaqs] = useState<CustomFAQ[]>(buildInitial())
  const [error, setError] = useState<string | null>(null)
  const [saving, setSaving] = useState(false)
  const [status, setStatus] = useState<string | null>(null)

  // Listen for unified form save event — save FAQ together
  useEffect(() => {
    const handler = () => void doSave()
    window.addEventListener('product-form-saved', handler)
    return () => window.removeEventListener('product-form-saved', handler)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [faqs])

  async function doSave() {
    setSaving(true)
    setError(null)
    setStatus(null)
    try {
      const res = await fetch(`/api/admin/products/${productId}/custom-faqs`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ faqs: faqs.filter(f => f.question.trim() && f.answer.trim()) }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error)
      setStatus(`✓ ${data.count ?? faqs.length} FAQ uloženo`)
      router.refresh()
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Chyba')
    } finally {
      setSaving(false)
    }
  }

  function addNew() {
    setFaqs(prev => [...prev, { question: '', answer: '', source: 'manual' }])
  }
  function update(i: number, patch: Partial<CustomFAQ>) {
    setFaqs(prev => prev.map((f, idx) => (idx === i ? { ...f, ...patch, source: 'manual' } : f)))
  }
  function remove(i: number) {
    setFaqs(prev => prev.filter((_, idx) => idx !== i))
  }
  function resetToAuto() {
    if (!confirm('Obnovit FAQ z automatických šablon? Tvé úpravy budou ztraceny.')) return
    setFaqs(autoGenerated.map(f => ({ question: f.question, answer: f.answer, source: 'auto' })))
  }

  return (
    <div className="bg-white border border-off2 rounded-[var(--radius-card)] p-6">
      <div className="flex items-start justify-between mb-4 gap-4">
        <div>
          <div className="text-sm font-semibold text-text">FAQ pro tento olej</div>
          <div className="text-xs text-text3 mt-0.5">
            Otázky zobrazené na produktové stránce v sekci „Často se ptáte na tento olej".
            Šedé = automaticky vygenerované z dat (uprav nebo nech). Olivové = manuální.
            Ukládá se s formulářem (💾 Uložit změny nahoře).
          </div>
        </div>
        <button
          type="button"
          onClick={resetToAuto}
          className="text-[11px] text-olive hover:text-olive-dark whitespace-nowrap"
        >
          ↻ Obnovit z auto
        </button>
      </div>

      <div className="space-y-2">
        {faqs.map((f, i) => (
          <div
            key={i}
            className={`rounded-lg border p-3 ${
              f.source === 'auto' ? 'bg-off border-off2' : 'bg-olive-bg/30 border-olive-border'
            }`}
          >
            <div className="flex items-center gap-2 mb-2">
              <span
                className={`text-[10px] uppercase tracking-wider font-bold px-2 py-0.5 rounded ${
                  f.source === 'auto'
                    ? 'bg-text3 text-text'
                    : 'bg-olive-dark text-text'
                }`}
              >
                {f.source === 'auto' ? 'AUTO' : 'MANUÁLNĚ'}
              </span>
              <button
                type="button"
                onClick={() => remove(i)}
                className="ml-auto text-text3 hover:text-amber-700 text-[12px]"
                title="Odstranit"
              >
                ✕
              </button>
            </div>
            <input
              type="text"
              value={f.question}
              onChange={e => update(i, { question: e.target.value })}
              placeholder="Otázka..."
              className="w-full px-2.5 py-1.5 border border-off2 rounded text-[13px] font-medium bg-white mb-1.5 focus:outline-none focus:border-olive"
            />
            <textarea
              value={f.answer}
              onChange={e => update(i, { answer: e.target.value })}
              rows={3}
              placeholder="Odpověď..."
              className="w-full px-2.5 py-1.5 border border-off2 rounded text-[12.5px] leading-relaxed bg-white focus:outline-none focus:border-olive"
            />
          </div>
        ))}
      </div>

      <div className="mt-3 flex items-center gap-2">
        <button
          type="button"
          onClick={addNew}
          className="text-[12px] text-olive hover:text-olive-dark"
        >
          + Přidat vlastní otázku
        </button>
        {saving && (
          <span className="ml-auto text-[11px] text-olive-dark bg-olive-bg border border-olive-border rounded px-2 py-0.5">
            Ukládám...
          </span>
        )}
        {status && (
          <span className="ml-auto text-[11px] text-olive-dark bg-olive-bg border border-olive-border rounded px-2 py-0.5">
            {status}
          </span>
        )}
        {error && (
          <span className="ml-auto text-[11px] text-red-700 bg-red-50 border border-red-200 rounded px-2 py-0.5">
            ⚠ {error}
          </span>
        )}
      </div>
    </div>
  )
}
