import { notFound } from 'next/navigation'
import Link from 'next/link'
import { supabaseAdmin } from '@/lib/supabase'
import { getAllRetailers, getOffersForProduct, getProductsByIds, getProductCustomFAQs } from '@/lib/data'
import { generateProductFAQ } from '@/lib/product-faq'
import { ProductForm } from './product-form'
import { OffersManager } from './offers-manager'
import { ImagePanel } from './image-panel'
import { FactsPanel, type ExtractedFact } from './facts-panel'
import { SourcePanel } from './source-panel'
import { GalleryManager } from './gallery-manager'
import { StatusActions } from './status-actions'
import { FAQPanel } from './faq-panel'
import { ParameterPanel } from './parameter-panel'
import { calculateCompleteness, completenessColor } from '@/lib/completeness'

async function getProductRow(id: string) {
  const { data, error } = await supabaseAdmin
    .from('products')
    .select('*')
    .eq('id', id)
    .maybeSingle()
  if (error) throw error
  return data
}

export default async function EditProductPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const [productRow, retailers] = await Promise.all([
    getProductRow(id),
    getAllRetailers(),
  ])
  if (!productRow) notFound()

  const [offers, productList, customFAQs] = await Promise.all([
    getOffersForProduct(id),
    getProductsByIds([id]),
    getProductCustomFAQs(id),
  ])
  const productTyped = productList[0]
  const autoFAQs = productTyped ? generateProductFAQ(productTyped, offers[0] ?? null) : []

  const status = productRow.status as string
  const publicUrl = `/olej/${productRow.slug as string}`
  const completeness = productTyped ? calculateCompleteness(productTyped) : null

  return (
    <div>
      <div className="text-xs text-zinc-500 mb-4">
        <Link href="/admin" className="text-olive">Admin</Link>
        {' › '}
        <Link href="/admin/products" className="text-olive">Produkty</Link>
        {' › '}
        {productRow.name as string}
      </div>
      <div className="flex items-start justify-between gap-4 mb-6 flex-wrap">
        <div>
          <h1 className="font-[family-name:var(--font-display)] text-3xl text-white">
            {productRow.name as string}
          </h1>
          {completeness && (
            <div className="mt-2 flex items-center gap-2">
              <span className={`text-[11px] ${completenessColor(completeness.weightedPercent).bg} ${completenessColor(completeness.weightedPercent).text} px-2.5 py-0.5 rounded-full font-medium`}>
                Komplet {completeness.weightedPercent}% ({completeness.filled}/{completeness.total} polí)
              </span>
              {completeness.missing.length > 0 && (
                <span className="text-[11px] text-zinc-500">
                  Chybí: {completeness.missing.slice(0, 5).map((m) => m.label).join(', ')}
                  {completeness.missing.length > 5 ? ` +${completeness.missing.length - 5}` : ''}
                </span>
              )}
            </div>
          )}
        </div>
        <StatusActions
          productId={id}
          currentStatus={status}
          publicUrl={publicUrl}
        />
      </div>

      <div className="space-y-6">
        <SourcePanel
          productId={id}
          sourceUrl={(productRow.source_url as string | null) ?? null}
          rawDescriptionLength={((productRow.raw_description as string | null) ?? '').length}
        />
        <ImagePanel
          productId={id}
          currentImageUrl={(productRow.image_url as string) ?? null}
          currentSource={(productRow.image_source as string) ?? null}
          ean={productRow.ean as string}
        />
        <GalleryManager productId={id} />
        <FactsPanel
          productId={id}
          initialFacts={
            Array.isArray(productRow.extracted_facts)
              ? (productRow.extracted_facts as ExtractedFact[])
              : []
          }
        />
        <ParameterPanel
          extractedFacts={
            Array.isArray(productRow.extracted_facts)
              ? (productRow.extracted_facts as Array<{ key: string; value: string }>)
              : []
          }
        />
        <ProductForm
          productRow={productRow}
          cheapestOfferPrice={offers[0]?.price ?? null}
        />
        <FAQPanel
          productId={id}
          autoGenerated={autoFAQs}
          initialCustomFAQs={customFAQs}
        />
        <OffersManager
          productId={id}
          productSlug={productRow.slug as string}
          retailers={retailers}
          initialOffers={offers}
        />
      </div>
    </div>
  )
}
