-- Editable FAQs — admin can manage general FAQs and add custom Q&As per product.

-- 1. Global / general FAQ (shown across all product pages, admin-curated)
CREATE TABLE IF NOT EXISTS general_faqs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  category VARCHAR(50) DEFAULT 'general', -- general / health / cooking / quality
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_general_faqs_active_order
  ON general_faqs(is_active, sort_order);

COMMENT ON TABLE general_faqs IS
  'Globální FAQ zobrazený na produktových stránkách. Admin spravuje přes /admin/faq.';

-- 2. Per-product custom FAQs — JSONB array of {question, answer, source: "auto" | "manual"}.
-- Auto = template-generated by lib/product-faq.ts (shown if not deleted).
-- Manual = admin-added or admin-edited override.
ALTER TABLE products ADD COLUMN IF NOT EXISTS custom_faqs JSONB DEFAULT '[]'::jsonb;

COMMENT ON COLUMN products.custom_faqs IS
  'Per-product FAQ overrides + extras. Array of {question, answer, source}.';
